### PR TITLE
Fix example and IOS scale mode

### PR DESCRIPTION
**Pull request by zcr1**
1) Example needs a `version` or flutter crashes on build
2) IOS is not providing `scale_mode` on initialization

### CODE REVIEW

**Comment by ruslan-trufanov** [comment]
what status of this issue ? (i need sacle mode on ios)

**Comment by zcr1** [comment]
I am not using this package anymore due to youtube's TOS but feel free to pull my changes in locally.

**Comment by zcr1** [comment]
I am no longer using this package but feel free to pull in my changes locally or wait for maintainer to merge. Someone will need to fix conflicts.

**Comment by rwrz** [comment]
> I am no longer using this package but feel free to pull in my changes locally or wait for maintainer to merge. Someone will need to fix conflicts.

just for curiosity, have you changed to which package?
I was using the youtube_player_flutter or something, and it has so many performance issues. This one is great!

**Comment by zcr1** [comment]
No issues with the package, project I was using it on was scrapped.

**Pull request closed without merging**
